// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaoOgt45rr64DCv1i8Y8_Nfdc4iiXrIno',
    appId: '1:557739804427:web:7583a3d3a0c9b92186440e',
    messagingSenderId: '557739804427',
    projectId: 'carval-373ea',
    authDomain: 'carval-373ea.firebaseapp.com',
    storageBucket: 'carval-373ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwaUKL1zY0IHV3NXkFSx2Z9CmWc2mfl4I',
    appId: '1:557739804427:android:585bb0f5c56507dc86440e',
    messagingSenderId: '557739804427',
    projectId: 'carval-373ea',
    storageBucket: 'carval-373ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKKN2iGYRnsfYyRZZHZ7Lc3SL7qWr55w',
    appId: '1:557739804427:ios:ad3431017baacea686440e',
    messagingSenderId: '557739804427',
    projectId: 'carval-373ea',
    storageBucket: 'carval-373ea.firebasestorage.app',
    iosBundleId: 'com.example.carVal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbKKN2iGYRnsfYyRZZHZ7Lc3SL7qWr55w',
    appId: '1:557739804427:ios:ad3431017baacea686440e',
    messagingSenderId: '557739804427',
    projectId: 'carval-373ea',
    storageBucket: 'carval-373ea.firebasestorage.app',
    iosBundleId: 'com.example.carVal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaoOgt45rr64DCv1i8Y8_Nfdc4iiXrIno',
    appId: '1:557739804427:web:539b93c48dce0eee86440e',
    messagingSenderId: '557739804427',
    projectId: 'carval-373ea',
    authDomain: 'carval-373ea.firebaseapp.com',
    storageBucket: 'carval-373ea.firebasestorage.app',
  );
}
